env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

settings:
  react:
    version: detect

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true

  ecmaVersion: latest
  sourceType: module

plugins: [react, "@typescript-eslint"]

rules:
  no-constant-condition: [error, { checkLoops: false }]
  camelcase: error
  eqeqeq: error
  max-statements: [error, 30]
  no-empty-function: error
  no-eval: error
  no-implied-eval: error
  no-throw-literal: error
