name: compile typescript
permissions:
  contents: read

on:
  push:
    paths:
      - "src/**"
    branches:
      - main
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile

      - run: bun run check
      - run: bun run build
