# This is a basic workflow to help you get started with Actions

name: compile typescript

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - "src/**"
    branches:
      - main

  pull_request:
    paths:
      - "src/**"
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: git config
        run: |
          git config --global user.email "github@example.com"
          git config --global user.name "github-actions"

      - run: git fetch
      - run: git checkout -b pages-build origin/pages-build
      - run: git merge --no-ff --allow-unrelated-histories -Xtheirs main

      - run: git rm -r javascript/*

      - run: npm ci

      - name: compile
        run: npm run build

      - name: git commit and push
        run: |
          git add .
          git commit -m "compile typescript"
          git push origin pages-build

      - name: always git state
        run: git status
        if: always()
